/* Async Actions */
export const REQUESTED_EVENTS = 'REQUESTED_EVENTS'
export const RECEIVED_EVENTS= 'RECEIVED_EVENTS'
export const ERROR_EVENTS = 'ERROR_EVENTS'

export const REQUESTED_SUPPLIERS = 'REQUESTED_SUPPLIERS'
export const RECEIVED_SUPPLIERS = 'RECEIVED_SUPPLIERS'
export const ERROR_SUPPLIERS = 'ERROR_SUPPLIERS'

export const DISMISSED_FILEUPLOAD_MODAL = 'DISMISSED_FILEUPLOAD_MODAL'
export const DISMISSED_REPORTS_MODAL = 'DISMISSED_REPORTS_MODAL'
export const OPENED_FILEUPLOAD_MODAL = 'OPENED_FILEUPLOAD_MODAL'
export const OPENED_REPORTS_MODAL = 'OPENED_REPORTS_MODAL'

export const CHANGED_ACTIVE_PROVIDER = 'CHANGED_ACTIVE_PROVIDER'

export const REQUESTED_LINE_STATS = 'REQUESTED_LINE_STATS'
export const RECEIVED_LINE_STATS = 'RECEIVED_LINE_STATS'
