/* Async Actions */
export const REQUESTED_EVENTS = 'REQUESTED_EVENTS'
export const RECEIVED_EVENTS= 'RECEIVED_EVENTS'
export const ERROR_EVENTS = 'ERROR_EVENTS'

export const REQUESTED_SUPPLIERS = 'REQUESTED_SUPPLIERS'
export const RECEIVED_SUPPLIERS = 'RECEIVED_SUPPLIERS'
export const ERROR_SUPPLIERS = 'ERROR_SUPPLIERS'

export const REQUESTED_LINE_STATS = 'REQUESTED_LINE_STATS'
export const RECEIVED_LINE_STATS = 'RECEIVED_LINE_STATS'
export const UPDATED_FILE_UPLOAD_PROGRESS_BAR = 'UPDATED_FILE_UPLOAD_PROGRESS_BAR'
export const UPDATED_FILE_UPLOAD_PROGRESS_BAR_STATE = 'UPDATED_FILE_UPLOAD_PROGRESS_BAR_STATE'

export const REQUESTED_FILES_FOR_PROVIDER = 'REQUESTED_FILES_FOR_PROVIDER'
export const RECEIVED_FILES_FOR_PROVIDER = 'RECEIVED_FILES_FOR_PROVIDER'
export const ERROR_FILES_FOR_PROVIDER = 'ERROR_FILES_FOR_PROVIDER'

/* User actions */
export const DISMISSED_FILEUPLOAD_MODAL = 'DISMISSED_FILEUPLOAD_MODAL'
export const DISMISSED_REPORTS_MODAL = 'DISMISSED_REPORTS_MODAL'
export const OPENED_FILEUPLOAD_MODAL = 'OPENED_FILEUPLOAD_MODAL'
export const OPENED_REPORTS_MODAL = 'OPENED_REPORTS_MODAL'

export const CHANGED_ACTIVE_PROVIDER = 'CHANGED_ACTIVE_PROVIDER'

/* file upload status */
export const FILE_UPLOAD_NOT_STARTED = 'FILE_UPLOAD_NOT_STARTED'
export const FILE_UPLOAD_UPLOADING = 'FILE_UPLOAD_UPLOADING'
export const FILE_UPLOAD_COMPLETED = 'FILE_UPLOAD_COMPLETED'
export const FILE_UPLOAD_FAILED = 'FILE_UPLOAD_FAILED'
